### ISSUE TITLE
dictionary.sip cannot be used due to large attibute values

### ISSUE THREAD

**Issue by twmobius** [FreeRADIUS/freeradius-client#103]
In order to use freeradius-client with kamailio/opensips etc one must include dictionary.sip file to the default dictionary. 

However currently the `directory.sip` file which is shipped with freeradius-client contains attributes with values greater than 255 (Digest-Realm, Digest-Nonce etc) which cause the library to fail to load the radiusclient.conf

The 255 limit was added with the commit of issue #72. (cc @mcpat) 

What is the best way to address this? Change the attribute values to less than 255? What is the point of the limit?

**Comment by alandekok** [comment]
RADIUS attributes are 8-bit, and have values `1..255`.  The Digest attributes are "internal", and aren't sent on the wire.

The patch from #88 allowed the code to use vendor numbers greater than 16 bits, but it also broke the ability to use "internal" attributes such as the Digest ones.

I've pushed a patch which _should_ help.  However, it's had minimal testing.

**Comment by twmobius** [comment]
@alandekok Wow, thanks Alan! I'm gonna apply the patch and get back to you

**Comment by twmobius** [comment]
@alandekok After a few days of fiddling around with this, it seems to be working properly.

**Comment by alandekok** [comment]
Thanks!

**Comment by twmobius** [comment]
Ok, it seems that there was one loose end with this that I just figured out. Please check this PR https://github.com/FreeRADIUS/freeradius-client/pull/106
