### ISSUE TITLE
User-password and shared secret limits too low, should be 128.

### ISSUE THREAD

**Issue by pem** [FreeRADIUS/freeradius-client#112]
If I understand RFC2865 correctly, the User-Password attribute should allow up to 128 octets. (Section "5.2 User-Password").
This was only 48 bytes in freeradiusclient 1.1.7, and in 1.1.8 it was increased, but only to 112 bytes (AUTH_PASS_LEN). The secret (MAX_SECRET_LENGTH) is still only 48 bytes however.

The shared secret is somewhat vaguely specified in the RFC, but in section "3 Packet Format" it's mentioned under "Authenticator" , "Request Authenticator":

> The NAS and RADIUS server share a secret. /.../ See the entry for User-Password in the section on Attributes for a more detailed description.

My interpretation is that the shared secret is treated the same way as User-Password and thus should have the same limit, 128 octets.

(The Azure server supports longer secrets at least, which is a customer ran into this issue.)

**Comment by alandekok** [comment]
I've bumped the limits for password to 128, and secrets to 256.

The RFCs are vague and confused about the secret.  The reference you quoted could mean almost anything.

Realistically, a secret of more than about 32 bytes is useless.  You could use base32 encoding and a 32-character secret to get 2^160 possible secrets.  That's something nobody can crack.

The only reason to have a longer secret is to have a *worse* one.  i.e. one which is easier to remember, and is therefore easier to guess.

**Comment by pem** [comment]
Thank you. Yes, I see no point in having such a long one either, which is the reason we didn't discover it ourselves in testing.

But customers do weird things, and I think it's an automated system, no human interaction, so remembering it isn't an issue for them.
