### ISSUE TITLE
website link issues

### ISSUE THREAD

**Issue by nmav** [FreeRADIUS/freeradius-client#38]
The website in http://freeradius.org/freeradius-client/
links to release 1.1.7 as: ftp://ftp.freeradius.org/pub/freeradius/freeradius-client-1.1.7.tar.bz2
This file doesn't exist. One can get the new release as: https://github.com/FreeRADIUS/freeradius-client/archive/release_1_1_7.tar.gz

The website also points to a wiki with outdated info at: http://wiki.freeradius.org/Radiusclient
(I was also unable to login either with github or openid at the wiki)
The best would have been to point to the github site instead (or in addition), which also has an issue tracker and does not require login to see the contents.

**Comment by alandekok** [comment]
I've fixed the link.  It's a gz, not a bz2.
