### ISSUE TITLE
No IPv6 support in radiusclient library

### ISSUE THREAD

**Issue by nmav** [FreeRADIUS/freeradius-client#42]
That's 2015 and IPv6 support is no luxury but a requirement for a library.

As I've previously mentioned, I have a patch set for it which depends on my existing 3 pull requests being merged. If you have no resources for them I volunteer to get that into freeradius-client, towards a 1.2.0 release.

**Comment by arr2036** [comment]
All your pull requests are now in. I agree IPv6 support is definitely no longer a luxury.
