### ISSUE TITLE
rc_avpair_gen discards all value pairs in case of an unknown attribute

### ISSUE THREAD

**Issue by mcpat** [FreeRADIUS/freeradius-client#71]
Currently, the code will discard all value pairs and stop processing further if an unknown attribute or unknown vendor attribute is found. Here, "unknown" refers to its absence in the dictionary (as far as I understand the code).

In our case this behaviour is inacceptible, because it would tie our client too close to the server (configurations). A better way would be 
1) either to ignore the attribute and proceed
2) or to attach the attribute to the list, storing the value to strvalue, length to lvalue and leaving the name empty.

**Comment by alandekok** [comment]
That has to be fixed.  It should just ignore unknown attributes, and pretend that they don't exist.

**Comment by mcpat** [comment]
Sorry for making a fuzz. As I see now, it's already fixed in the master. I checked against the release branch which seems to be a little bit behind.
