### ISSUE TITLE
choosing a specific outgoing interface

### ISSUE THREAD

**Issue by sfordinc** [FreeRADIUS/freeradius-client#73]
Hello!
Why is there no option in rad_client (radtest) for choosing a specific outgoing interface, like -I eth0?
This option will save on the hosts for testing the interaction of rad_clients with a free radius server.

**Comment by alandekok** [comment]
Your OS should take care of routing packets.

There is nothing in RADIUS which is specific to an ethernet interface.

**Comment by sfordinc** [comment]
But if send packets in one radius server address from rad clients then all packets will sent via one net interface.

**Comment by alandekok** [comment]
That's how IP routing works.

**Comment by sfordinc** [comment]
I didn't understand your last comment.
The problem exists, and you don't want it fundamentally solved, adding described me the opportunity, or you don't see a problem, as there is another way to achieve the desired result?

**Comment by alandekok** [comment]
> I didn't understand your last comment.

That much is clear.

Let me make it simple.  You use the word "interface".  In normal uses of the term, this means "ethernet interface".  As I said above, RADIUS isn't aware of ethernet interfaces.  It works based on source and destination IP addresses.

> The problem exists, and you don't want it fundamentally solved,

Don't be rude.  It shows a complete lack of social skills.

> adding described me the opportunity, or you don't see a problem, as there is another way to achieve the desired result?

I have no idea what you actually want to do.  If you say "interface" and mean "ethernet interface", then my explanation is correct, and the "problem" you describe doesn't exist.

If you say "interface" and mean something *else*, other than "ethernet interface", then you need to explain what you mean using *standard networking words*.

To be honest, it looks like you have no idea how networking works, which means you're using the wrong words to describe things.  When I use the correct words, it just confuses you.

Please stop arguing here, and go learn how networks work.  Then, open another issue using *standard networking words* to describe what you want.
