### ISSUE TITLE
radius by xl2tpd

### ISSUE THREAD

**Issue by clacki** [FreeRADIUS/freeradius-client#77]
Hello,

I fix radius for pptpd by = radiusclient-0.3.2
I have problem by radius in xl2tpd by this radiusclient .
Give me this Error :

Aug 11 08:37:58 localhost xl2tpd[3141]: death_handler: Fatal signal 15 received
Aug 11 08:37:59 localhost xl2tpd[15268]: setsockopt recvref[30]: Protocol not available
Aug 11 08:37:59 localhost xl2tpd[15268]: Using l2tp kernel support.
Aug 11 08:37:59 localhost xl2tpd[15269]: xl2tpd version xl2tpd-1.3.8 started on shayan PID:15269
Aug 11 08:37:59 localhost xl2tpd[15269]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Aug 11 08:37:59 localhost xl2tpd[15269]: Forked by Scott Balmos and David Stipp, (C) 2001
Aug 11 08:37:59 localhost xl2tpd[15269]: Inherited by Jeff McAdams, (C) 2002
Aug 11 08:37:59 localhost xl2tpd[15269]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Aug 11 08:37:59 localhost xl2tpd[15269]: Listening on IP address 0.0.0.0, port 1701
Aug 11 08:38:26 localhost xl2tpd[15269]: Connection established to 11.11.11.11, 12969. Local: 26402, Remote: 22 (ref=0/0). LNS session is 'default'
Aug 11 08:38:26 localhost xl2tpd[15269]: Call established with 11.11.11.11, Local: 15176, Remote: 1, Serial: 0
Aug 11 08:38:26 localhost pppd[15281]: Plugin pppol2tp.so loaded.
Aug 11 08:38:26 localhost pppd[15281]: Plugin radius.so loaded.
Aug 11 08:38:26 localhost pppd[15281]: RADIUS plugin initialized.
Aug 11 08:38:26 localhost pppd[15281]: Plugin radattr.so loaded.
Aug 11 08:38:26 localhost pppd[15281]: RADATTR plugin initialized.
Aug 11 08:38:26 localhost pppd[15281]: pppd 2.4.5 started by root, uid 0
Aug 11 08:38:26 localhost pppd[15281]: Using interface ppp0
Aug 11 08:38:26 localhost pppd[15281]: Connect: ppp0 <-->
Aug 11 08:38:27 localhost pppd[15281]: rc_avpair_new: unknown attribute 60
Aug 11 08:38:27 localhost pppd[15281]: rc_avpair_gen: received unknown attribute 85 of length 4: 0x0000003C
Aug 11 08:38:27 localhost pppd[15281]: Peer test failed CHAP authentication
Aug 11 08:38:27 localhost pppd[15281]: Connection terminated.
Aug 11 08:38:27 localhost pppd[15281]: Exit.
Aug 11 08:38:27 localhost xl2tpd[15269]: control_finish: Connection closed to 11.11.11.11, serial 0 ()
Aug 11 08:38:27 localhost xl2tpd[15269]: control_finish: Connection closed to 11.11.11.11, port 12969 (), Local: 26402, Remote: 22

**Comment by alandekok** [comment]
We have released radiusclient 1.1.6.   Version 0.3.2 is a decade old.

Please upgrade to a recent version of the software.

**Comment by clacki** [comment]
@alandekok Give me link of this package please . (centos 6.9 64bit)

**Comment by arr2036** [comment]
We don't package freeradius-client currently, you'll need to build from source.

**Comment by clacki** [comment]
@arr2036 I install radiusclient 0.3.2 from this link : ftp://ftp.ru.debian.org/gentoo-distfiles/distfiles/radiusclient-0.3.2.tar.gz
and extract and make files .
I don't know how install radiusclient 1.1.6 .!

**Comment by arr2036** [comment]
http://freeradius.org/sub_projects/ click the freeradius-client heading.  @mcnewton really need to make those anchors so they're linkable.
