### ISSUE TITLE
freeradius-clinet that supports PAM & PEAP/TLS-EAP

### ISSUE THREAD

**Issue by mlnx-omrigi** [FreeRADIUS/freeradius-client#86]
Hi,
Is there any way to use this freeradius-client with Linux PAM and TLS connection?
I saw that TLS is **not supported** in pam_radius_auth, so I'm asking in this repository because I saw that freeradius-client **does** support TLS.

Thanks,
Omri.

**Comment by alandekok** [comment]
freeradius-client doesn't support TLS.  The PAM module doesn't support TLS either.

Realistically, it's better to use UDP for local networks.  If you need to send RADIUS packets across the wider Internet, then you need a full-featured RADIUS server.  There's a lot more than just TLS involved.  e.g. fail-over, load-balancing, statistics, etc.
