### ISSUE TITLE
make a 1.1.7 tag please

### ISSUE THREAD

**Issue by dpocock** [FreeRADIUS/freeradius-client#9]
Would you consider tagging a 1.1.7 release?

I would then use that to make up a fresh version of the Debian and Ubuntu packages

**Comment by codehero** [comment]
I want to make a package for buildroot and a tag would be very helpful!

**Comment by alandekok** [comment]
I've released version 1.1.7.  Let me know if there are any issues.

**Comment by codehero** [comment]
A release is a good thing, but for those of us who may need to make downstream modifications to the build environment, etc we would need an official tag on a git revision.

Buildroot also has support for referencing a package hosted on github by just using a tag revision. This would help expand freeradius to this userbase.

**Comment by alandekok** [comment]
done.  see release_1_1_7
