### ISSUE TITLE
Accounting only configuration

### ISSUE THREAD

**Issue by tuxford** [FreeRADIUS/freeradius-client#95]
If no authentication is set up but only accounting is set up, client doesn't work. But it common case when only accounting or authorization is used. Why does current implementation deny that?

**Comment by alandekok** [comment]
The API allows for you to send only accounting packets.  See `radacct.c` as an example.

**Comment by tuxford** [comment]
Are you sure?
I've just build and run with next config below. Result in syslog:  "/home/rluchishin/tmp/radiusclient.conf: no authserver specified"
I see test_config doesn't pass if there is no authserver specified. 
I use radacct.

--- 
auth_order      radius,local
login_tries     4
login_timeout   60
nologin /etc/nologin
issue   /etc/radiusclient/issue
acctserver 192.168.19.187:1813
servers         /etc/radiusclient/servers
dictionary      /etc/radiusclient/dictionary
login_radius    /usr/sbin/login.radius
mapfile         /etc/radiusclient/port-id-map
default_realm
radius_timeout  4
radius_retries  1
radius_deadtime 0
bindaddr *
login_local     /bin/login

**Comment by alandekok** [comment]
It helps to give a *good description* of the problem when you open an issue.

The API is completely capable of sending just accounting packets.  The only issue is the `test_config()` function, which should be fixed.

I'd be happy to accept a patch to fix this.
